DROP TABLE IF EXISTS post;

CREATE TABLE post (
    id INT NOT NULL AUTO_INCREMENT,
    title VARCHAR(64) NOT NULL,
    body VARCHAR(65536) NOT NULL,
    date_ DATETIME NOT NULL,
    PRIMARY KEY (id)
);
